### ISSUE TITLE
[1.4.0] TypeError: done is not a function in deploy

### ISSUE THREAD

**Issue by ankon** [finn-no/maven-deploy#31]
Seen with gulp-maven-deploy 0.2.0/0.2.1 and maven-deploy 1.4.0:

~~~~
archive path dist/collaborne-login-app.war
Executing command: mvn -B deploy:deploy-file -Dpackaging=war -Dfile=dist/collaborne-login-app.war -DgroupId=com.collaborne.app -DartifactId=collaborne-login-app -Dversion=1.0.0-SNAPSHOT -DrepositoryId=collaborne-snapshot-repository -Durl=s3://collaborne-repository/maven/collaborne-snapshots
/home/andreas/project/collaborne-login-app/node_modules/maven-deploy/index.js:117
        if (done) { done(err, stdout, stderr); }
                    ^

TypeError: done is not a function
    at /home/andreas/project/collaborne-login-app/node_modules/maven-deploy/index.js:117:21
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
~~~~

The same build works with maven-deploy 1.3.0.

**Comment by micha149** [comment]
@gregersrygg Damn. I tested only the new behavior and didn't ensure that the old usage still works… Is it possible to get this done quickly. All deploys of depending project are failing currently…

**Comment by gregersrygg** [comment]
Ouch! Didn't see this until now :grimacing: Thought I had covered all ways to call the different functions in the unit tests, but had a bug the tests didn't catch. Sorry folks!

Released 1.4.1 now that should fix the problem.
