### PR TITLE
Fix the logic for handling optional parameters in `deploy`

### LINKED ISSUE #31: [1.4.0] TypeError: done is not a function in deploy
Seen with gulp-maven-deploy 0.2.0/0.2.1 and maven-deploy 1.4.0:

~~~~
archive path dist/collaborne-login-app.war
Executing command: mvn -B deploy:deploy-file -Dpackaging=war -Dfile=dist/collaborne-login-app.war -DgroupId=com.collaborne.app -DartifactId=collaborne-login-app -Dversion=1.0.0-SNAPSHOT -DrepositoryId=collaborne-snapshot-repository -Durl=s3://collaborne-repository/maven/collaborne-snapshots
/home/andreas/project/collaborne-login-app/node_modules/maven-deploy/index.js:117
        if (done) { done(err, stdout, stderr); }
                    ^

TypeError: done is not a function
    at /home/andreas/project/collaborne-login-app/node_modules/maven-deploy/index.js:117:21
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
~~~~

The same build works with maven-deploy 1.3.0.

### PR DESCRIPTION
**Pull request by ankon**
Fixes #31

### CODE REVIEW

**Comment by micha149** [comment]
@ankon I came to this issue, too. Can you please provide a test which fails with the previous code? The fix you made seems to be ok.

**Comment by ankon** [comment]
The reason the existing tests didn't fail is that they always had 'isSnapshot' set to `false`, thereby never triggering the faulty second condition. I've modified them now to test with both `true` and `false`.

Somehow I have the feeling that the first part of the condition is actually faulty as well, and actually could be dropped completely. Trying to come up with a case for that, but will then file another issue.

**Comment by micha149** [comment]
I think doing some tests with {{isSnapshot = true}} is ok for this issue. So it is a bit better documented, that we had a problem here and further changes will not bring these kind of problem up again…

**Comment by gregersrygg** [comment]
Sorry, I started looking at solving the issue before I looked at the pull-requests. Ended up with almost exactly the same fix, so won't merge this.

As a thank you, I've given both of you commit-access.

**Comment by ankon** [comment]
Thanks! Tested the new version, and it solves the issue nicely.
